baseURL = "https://www.aleixalcacer.com"
title = "Aleix Alcacer"
theme = "PaperMod"
pygmentsUseClasses = true

[frontmatter]
date = [":filename", ":default"]
publishDate = [":filename", ":default"]

[permalinks]
posts = "posts/:year/:month/:day/:slug/"

[params]
mathjax = true
showReadingTime = true

# Shown on the home page
socialIcons = [
  { name = "email", url = "mailto:aleixalcacer@gmail.com" },
  { name = "github", url = "https://github.com/aleixalcacer" },
  { name = "twitter", url = "https://twitter.com/aleixalcacer" },
  { name = "stackoverflow", url = "https://stackoverflow.com/users/14079719"},
  { name = "linkedin", url = "https://www.linkedin.com/aleixalcacer/" },
]

# Disable Highlight JS
[params.assets]
disableHLJS = true

# Configure the home page
[params.profileMode]
enabled = true
imageurl = "/avatar.jpeg"
title = "Hi, I'm Aleix Alcacer."
subtitle = ""

# Site-wide navigation
[[menu.main]]
weight = 1
identifier = "about"
name = "About"
title = "About"
url = "/about/"

[[menu.main]]
weight = 2
identifier = "blog"
name = "Blog"
title = "Blog"
url = "/blog/"

[[menu.main]]
weight = 3
identifier = "resume"
name = "Resume"
title = "Resume"
url = "/resume/"

# [[menu.main]]
# weight = 4
# identifier = "other stuff"
# name = "other stuff"
# title = "Other stuff"
# url = "/stuff/"
